# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
---
language: en-US
tone_instructions: "Be direct and concise. Focus on correctness of semver logic and conventional commit parsing."
early_access: true

reviews:
  auto_review:
    enabled: true
    drafts: false
  path_instructions:
    - path: src/bumper.js
      instructions: |
        Core semver bumping logic. Review for:
        - Correct semantic versioning calculations
        - Proper handling of 'v' prefix preservation (v1.2.3 -> v1.2.4)
        - Edge cases: no tags (defaults to 1.0.0), invalid semver, breaking changes
        - Conventional commit parsing via conventional-recommended-bump
        - Dev label must start with hyphen per semver spec
    - path: src/cli.js
      instructions: |
        CLI entrypoint using minimist. Review for:
        - Backward compatibility of deprecated aliases (repopath -> repo, bumpoverride -> bump)
        - Correct option parsing and defaults
        - Help text accuracy matching actual behavior
    - path: src/index.js
      instructions: |
        ES module entrypoint. Review for correct default option merging.
    - path: tests/**/*.js
      instructions: |
        Mocha/Chai tests. Review for coverage of:
        - Manual bumps (major/minor/patch with various labels)
        - Auto bumps from git (fix->patch, feat->minor, BREAKING CHANGE->major)
        - Error cases (invalid semver, unreachable path, non-git folder, bad labels)
        - Edge case: no existing tags
    - path: Dockerfile
      instructions: |
        Review for:
        - Minimal image size (node:slim base, apt cleanup)
        - Security (non-root 'node' user, safe.directory config)
        - Correct WORKDIR (/repo) and ENTRYPOINT
    - path: .github/workflows/*.yml
      instructions: |
        GitHub Actions workflows. Review for:
        - Correct trigger conditions
        - Proper use of reusable workflows
        - Security (minimal permissions)

chat:
  auto_reply: true
