# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
---
reviews:
  path_instructions:
    - path: src/**/*.js
      instructions: |
        Review JavaScript code for:
        - Proper async/await and Promise handling
        - Conventional commit parsing accuracy
        - Semantic versioning logic correctness
        - Clear error messages
    - path: tests/**/*.js
      instructions: |
        Review test code for:
        - Comprehensive version bump scenarios
        - Edge case coverage for commit parsing
        - Clear test descriptions
    - path: Dockerfile
      instructions: |
        Review Dockerfile for:
        - Minimal image size
        - Security best practices
