---
root: true
parserOptions:
  ecmaVersion: latest
env:
  node: true
  commonjs: true
  mocha: true
  shelljs: true
extends:
  - "eslint:recommended"
  - "plugin:editorconfig/all"
plugins:
  - "editorconfig"
