---
name: Bug Report
description: File a bug report
labels: ["type: bug"]

body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also share, what did you expect to happen?
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of `version-bumper` are you using?
      placeholder: ex. 4.0.6
    validations:
      required: true

  - type: textarea
    id: log-output
    attributes:
      label: Relevant log output
      description: Please provide any relevant log output. Check for private info before submitting.
      render: shell
